### ISSUE TITLE
Update Year in Footer

### ISSUE THREAD

**Issue by github-quest** [github-quest/github-quest.github.io#53]

**Comment by Anish-Sarawgi** [comment]
I want to work on this issue.

**Comment by Shivam164** [comment]
Hey @github-quest, I would like to work on this. Please assign this to me.

**Comment by SainathPoojary** [comment]
Hey @github-quest, I have raised a PR. Do let me know if you need any changes.

**Comment by github-quest** [comment]
@Anish-Sarawgi Update the Year in Contact Page

**Comment by github-quest** [comment]
@SainathPoojary PR Merged for Year Change in Index Page

**Comment by github-quest** [comment]
@Shivam164 you can work on other issues, this issue is almost resolved
